import re

with open('professionnels-mock.html', 'r', encoding='utf-8') as f:
    html = f.read()

replacements = {
    "A first functional agent: 4-8 weeks of co-construction.": "Un premier agent fonctionnel : 4-8 semaines en co-construction.",
    "A mid-sized architecture firm managed 15-20 projects simultaneously. Regulatory watch (urban planning, safety, environment) was done manually and caused compliance delays.": "Un cabinet d'architecture de taille moyenne gérait 15-20 projets simultanément. La veille réglementaire (urbanisme, sécurité, environnement) était faite manuellement et causait des retards de conformité.",
    "A multi-mandate manager struggled to follow news on 80+ positions while providing personalized reporting to each client.": "Un gérant multi-mandats peinait à suivre l'actualité de plus de 80 positions tout en fournissant un reporting personnalisé à chaque client.",
    "AWS certifications, up-to-date stack, cloud-native architectures": "Certifications AWS, stack à jour, architectures cloud-native",
    "After years in consulting firms and asset management, we've observed many issues: six-figure engagements that lead nowhere, consultants who disappear after their report, promises rarely kept.": "Après des années en cabinet de conseil et gestion d'actifs, nous avons observé de nombreux problèmes : des engagements à six chiffres qui ne mènent nulle part, des consultants qui disparaissent après leur rapport, des promesses rarement tenues.",
    "An equity research team received 200+ newsletters and reports daily. Manual synthesis for credit notes and market updates took 2-3 days per week.": "Une équipe d'analyse financière recevait plus de 200 newsletters et rapports par jour. La synthèse manuelle pour les notes de crédit et les mises à jour du marché prenait 2-3 jours par semaine.",
    "Architect": "Architecte",
    "Asset Manager": "Gestion d'actifs",
    "At Bubble Invest, we chose to do things differently: betting on honesty and the real desire to help — even if it means sometimes saying no to a project.": "Chez Bubble Invest, nous avons choisi de faire les choses différemment : parier sur l'honnêteté et la volonté d'aider — quitte à refuser un projet.",
    "Autonomy from day one": "Autonomie dès le premier jour",
    '>Autonomy<': '>Autonomie<',
    "Better than advice — solutions.": "Mieux que des conseils — des solutions.",
    ">Book a call<": ">Prendre rendez-vous<",
    "Co-construction with your teams": "Co-construction avec vos équipes",
    "Concrete Examples": "Exemples concrets",
    "Continuous support after go-live": "Support continu après la mise en production",
    "Credit Notes & Market Research Writing Agent": "Agent de Rédaction de Notes de Crédit & Études de Marché",
    "Diagnostic of your processes and quick wins": "Diagnostic de vos processus et quick wins",
    ">Discovery<": ">Découverte<",
    "Documentation and knowledge transfer": "Documentation et transfert de connaissances",
    "Entrepreneur": "Entrepreneur",
    "Equity Research": "Analyse Financière",
    "Ex: \"Automate my monthly reporting\" or \"Watch my investment sectors\"": "Ex : \"Automatiser mon reporting mensuel\" ou \"Surveiller mes secteurs d'investissement\"",
    "Finance": "Finance",
    "First contact": "Premier contact",
    "How long does it take?": "Combien de temps ça prend ?",
    "How we work": "Comment nous travaillons",
    "Independent Wealth Advisor": "CGP indépendant",
    "Integration with your existing systems": "Intégration avec vos systèmes existants",
    "Learning by doing — no theoretical training": "Apprentissage par la pratique — pas de formation théorique",
    "Let's discuss your project": "Discutons de votre projet",
    "Live sessions on your real projects": "Sessions en direct sur vos vrais projets",
    "Modern stack (OpenClaw, MCP) — not old tools": "Stack moderne (OpenClaw, MCP) — pas d'anciens outils",
    "Native expertise in regulatory issues, risks, business workflows": "Expertise native des enjeux réglementaires, risques, workflows métiers",
    "Normative surveillance agent": "Agent de surveillance normative",
    "Not 6 months of theoretical study. We build from the first session. You see results every week.": "Pas 6 mois d'étude théorique. Nous construisons dès la première session. Vous voyez des résultats chaque semaine.",
    "Not tools hyped 2 years ago (like n8n or Make).": "Pas des outils hype d'il y a 2 ans (comme n8n ou Make).",
    "OpenClaw, market APIs, LLM for synthesis, vector database for contextual memory per client": "OpenClaw, APIs de marché, LLM pour la synthèse, base de données vectorielle pour mémoire contextuelle par client",
    "Operational mastery of latest models, continuous watch": "Maîtrise opérationnelle des derniers modèles, veille continue",
    "Our Difference": "Notre Différence",
    "Our Methodology": "Notre Méthodologie",
    "Portfolio Monitoring & News Intelligence Platform": "Plateforme de Veille d'Actus & Suivi de Portefeuille",
    "RAG on internal corpus, LLM with fine-tuning on writing style, multi-source workflow": "RAG sur corpus interne, LLM avec fine-tuning sur le style d'écriture, workflow multi-sources",
    "Rare triple expertise": "Triple expertise rare",
    "Real-time explanations of choices": "Explication des choix en temps réel",
    "Regulatory Watch Agent for Architects": "Agent de Veille Réglementaire pour Architectes",
    "Result:": "Résultat :",
    "Roadmap for priority automations": "Feuille de route des automatisations prioritaires",
    "Smart scraping, LLM classification, geographic filtering, email/Slack alerts": "Scraping intelligent, classification LLM, filtrage géographique, alertes email/Slack",
    "Solution:": "Solution :",
    "Synthesis and writing agent": "Agent de synthèse et de rédaction",
    "Tech:": "Tech :",
    "That's the goal!": "C'est l'objectif !",
    "They Trust Us": "Ils nous font confiance",
    "Two interconnected agents": "Deux agents interconnectés",
    "We come from the business (Deloitte, UBS), not pure dev. We speak your language and we train your teams as we build. No technical prerequisite required.": "Nous venons du métier (Deloitte, UBS), pas du pur développement. Nous parlons votre langage et formons vos équipes pendant que nous construisons. Aucun prérequis technique requis.",
    "We document everything — code, prompts, processes. From day one, you can take over. We succeed when you no longer need us.": "Nous documentons tout — code, prompts, processus. Dès le premier jour, vous pouvez prendre le relais. Notre succès, c'est quand vous n'avez plus besoin de nous.",
    "We don't have a tech team internally. Does it still work?": "Nous n'avons pas d'équipe tech en interne. Ça marche quand même ?",
    "What if we want to stop working with you?": "Et si nous voulons arrêter de travailler avec vous ?",
    "What our first clients say": "Ce que disent nos premiers clients",
    "What we have deployed": "Ce que nous avons déployé",
    "Why work with us": "Pourquoi travailler avec nous",
    "Yes — that's exactly why we exist.": "Oui — c'est exactement pour cela que nous existons.",
    "Your questions, our answers": "Vos questions, nos réponses",
    "Your team gains skills on latest tools": "Votre équipe monte en compétence sur les derniers outils",
    "Context:": "Contexte :",
    "30 minutes to identify what's worth automating — free, no commitment": "30 minutes pour identifier ce qui vaut le coup d'automatiser — gratuit, sans engagement",
    "• 0 compliance delays since deployment": "• 0 retard de conformité depuis le déploiement",
    "• 3h saved every morning on watch": "• 3h gagnées chaque matin sur la veille",
    "• 70% reduction in note writing time": "• 70% de réduction du temps de rédaction des notes",
    "• Automatic reading of sources (newsletters, reports, filings) by theme and sector": "• Lecture automatique des sources (newsletters, rapports, bilans) par thème et secteur",
    "• Better coverage: nothing slips through anymore": "• Meilleure couverture : rien ne passe à travers les mailles du filet",
    "• Contextualized alerts: \"Your project X in zone Y is affected by new standard Z\"": "• Alertes contextualisées : \"Votre projet X en zone Y est affecté par la nouvelle norme Z\"",
    "• Daily scan of regulatory updates (building codes, decrees, circulars) by project type and location": "• Scan quotidien des mises à jour réglementaires (codes de l'urbanisme, décrets, etc.) par projet et emplacement",
    "• Improved opportunity/risk detection (+40% coverage)": "• Amélioration de la détection opportunité/risque (+40% de couverture)",
    "• Instant client reporting (instead of 2 days)": "• Reporting client instantané (au lieu de 2 jours)",
    "• Key point extraction: figures, guidance, narrative changes": "• Extraction des points clés : chiffres, prévisions, changements de narration",
    "• Metrics agent — Calculates in real-time: sharpe, vol, drawdown, correlation, custom ESG scoring": "• Agent de quant. — Calcule en temps réel : sharpe, vol, drawdown, corrélation, scoring ESG (custom)",
    "• Monthly synthesis per project of relevant updates": "• Synthèse mensuelle par projet des mises à jour pertinentes",
    "• News watch agent — Scans 50+ sources every morning, identifies relevant news by position, generates a personalized brief per portfolio": "• Agent de veille d'actualité — Scanne 50+ sources chaque matin, filtre l'actualité par position, génère un brief personnalisé",
    "• Peace of mind: nothing slips through the cracks": "• Tranquillité d'esprit : rien ne passe inaperçu",
    "• Portfolio position watch: alert if a held security is mentioned negatively": "• Veille des positions du portefeuille : alerte si un titre est mentionné négativement",
    "• Structured note draft generation (summary, pros/cons, impacts)": "• Génération d'un brouillon de note structuré (résumé, pour/contre, impacts)",
    "• Team focuses on qualitative analysis and decisions, not information gathering": "• L'équipe se concentre sur l'analyse qualitative et les décisions, pas sur la collecte d'informations",
    "• Watch time divided by 5": "• Temps de veille divisé par 5"
}

for eng, fr in replacements.items():
    html = html.replace(eng, fr)

with open('professionnels-mock.html', 'w', encoding='utf-8') as f:
    f.write(html)
